/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by VibeStack — do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AboutImport } from './routes/about'
import { Route as ContactImport } from './routes/contact'
import { Route as RecipesListImport } from './routes/recipes/index'
import { Route as RecipesDetailImport } from './routes/recipes/$id'
import { Route as IngredientsListImport } from './routes/ingredients/index'
import { Route as IngredientsDetailImport } from './routes/ingredients/$id'
import { Route as RecipeTagsListImport } from './routes/recipe-tags/index'
import { Route as RecipeTagsDetailImport } from './routes/recipe-tags/$id'
import { Route as RecipeTagMapsListImport } from './routes/recipe-tag-maps/index'
import { Route as RecipeTagMapsDetailImport } from './routes/recipe-tag-maps/$id'

const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)
const AboutRoute = AboutImport.update({ path: '/about', getParentRoute: () => rootRoute } as any)
const ContactRoute = ContactImport.update({ path: '/contact', getParentRoute: () => rootRoute } as any)

const RecipesListRoute = RecipesListImport.update({ path: '/recipes/', getParentRoute: () => rootRoute } as any)
const RecipesDetailRoute = RecipesDetailImport.update({ path: '/recipes/$id', getParentRoute: () => rootRoute } as any)
const IngredientsListRoute = IngredientsListImport.update({ path: '/ingredients/', getParentRoute: () => rootRoute } as any)
const IngredientsDetailRoute = IngredientsDetailImport.update({ path: '/ingredients/$id', getParentRoute: () => rootRoute } as any)
const RecipeTagsListRoute = RecipeTagsListImport.update({ path: '/recipe-tags/', getParentRoute: () => rootRoute } as any)
const RecipeTagsDetailRoute = RecipeTagsDetailImport.update({ path: '/recipe-tags/$id', getParentRoute: () => rootRoute } as any)
const RecipeTagMapsListRoute = RecipeTagMapsListImport.update({ path: '/recipe-tag-maps/', getParentRoute: () => rootRoute } as any)
const RecipeTagMapsDetailRoute = RecipeTagMapsDetailImport.update({ path: '/recipe-tag-maps/$id', getParentRoute: () => rootRoute } as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ContactRoute,
  RecipesListRoute,
  RecipesDetailRoute,
  IngredientsListRoute,
  IngredientsDetailRoute,
  RecipeTagsListRoute,
  RecipeTagsDetailRoute,
  RecipeTagMapsListRoute,
  RecipeTagMapsDetailRoute,
])
